# Generated by Django 5.0.6 on 2024-06-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=models.TextField(default='I love'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='Female', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='grade_level',
            field=models.IntegerField(default=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='id_number',
            field=models.IntegerField(default=1002),
            preserve_default=False,
        ),
    ]
